### ISSUE TITLE
Problem in install-openshift.sh

### ISSUE THREAD

**Issue by dsandersAzure** [gshipley/installcentos#110]
Hi, I spent a few hours going through the install today to stand up OKD 3.11 and had some issues that I couldn't get around. I want to document the eventual steps I took to get this working here, so I could share them with others:

1. Watch the video - you may be tempted to skip it but it's important to watch at least the start because if you skip it you miss `yum install git docker net-tools`; originally, I tried to use the Docker CE 18.x release which *does not* work; I suggest this is called out in the instructions to explicitly do `yum install git docker net-tools` - I was in an open plan area and couldn't watch the video.

2. After cloning the repo and cd'ing to it and running `./install-openshift.sh`, it started well but gave lots of 'oc command not found' errors. I eventually tracked the problems to lines 157 and 158 in the shell file:
```
ansible-playbook -i inventory.ini openshift-ansible/playbooks/prerequisites.yml
ansible-playbook -i inventory.ini openshift-ansible/playbooks/deploy_cluster.yml
```
My shell reported that it couldn't find those playbooks and I had to edit the .sh file and change it to:
```
ansible-playbook -i inventory.ini /root/installcentos/openshift-ansible/playbooks/prerequisites.yml
ansible-playbook -i inventory.ini /root/installcentos/openshift-ansible/playbooks/deploy_cluster.yml
```

After that, the install worked perfectly and completed. I had set my domain to be my ip (just for testing). I could browse to my ip (192.168.0.16:8443) but the redirect then went to console.192.168.0.16, so I had to add an entry for console.192.168.0.16 in /etc/hosts.

After that the web UI appeared and, so far, everything looks good.

Thanks for the repo and hopefully someone else can benefit from the above.

David

**Comment by marekjelen** [comment]
Hi,

1. Thanks, have updated the README to state the system should be clean CentOS. OpenShift only supports Docker 1.13 or CRI-O 1.11 (https://docs.openshift.com/container-platform/3.11/release_notes/ocp_3_11_release_notes.html)

2. that is weird, if you were in the `installcentos` directory, ti should work. though this way is not really supported. The script should be used without cloning the repo locally. In case there is security problem with piping from internet to bash (which should be), the script should be downloaded, verified and run, but still without the clone :)

3. the redirect should go to the `console.` prefix, however it should have been `console.192.168.0.16.nip.io:8443` the `nip` domain sare used, unless the user sets up their own DNS records, as they do not require changing the `hosts` file.

**Comment by dsandersAzure** [comment]
@marekjelen Thanks for the reply - much appreciated :) 👍
