### ISSUE TITLE
Stick to release-3.11 version

### ISSUE THREAD

**Issue by vrutkovs** [gshipley/installcentos#124]
https://github.com/gshipley/installcentos/blob/080a0cf7398f0e9ebe1c30b4da952116a03b9e1d/install-openshift.sh#L89

Very soon master version would be rewritten to use a new Openshift version. Users should stick to `release-3.11` branch for now

**Comment by melledouwsma** [comment]
I believe this issue could be closed. It has been resolved since #150 was merged into the repository. Thank you.
