### ISSUE TITLE
Service Catalog Install Failed.

### ISSUE THREAD

**Issue by fuguman** [gshipley/installcentos#18]
Dear @gshipley 
My Name is Shuichi Ikegami.
your contents is very nice! 
but, I executed a task and the following message occurred.
---------------------------------------------------------------------
TASK [openshift_service_catalog : wait for api server to be ready]
FAILED - RETRYING: wait for api server to be ready (1 retries left).
0curl: (7) Failed connect to apiserver.kube-service-catalog.svc:443; Connection refused"], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/root/installcentos/openshift-ansible/playbooks/byo/config.retry
----------------------------------------------------------------------------
Connection to the Openshift server seems to have problems with name resolution, so it resolved, but how to retry Ansible's Playbook?

**Comment by fuguman** [comment]
I closed the issue registered with the introduction of service catalog because it was the same failure on YouTube as well.

**Comment by fuguman** [comment]
I closed the issue registered with the introduction of service catalog because it was the same failure on YouTube as well.

**Comment by MariuSteinbach** [comment]
Hi,
I'm experiencing the same error.
Can you show me the video, where this error is happening too? a cant see it and my openshift isn't running after the installation.

thank you!
