### ISSUE TITLE
simplephp is build OK, but deploy is failed.

### ISSUE THREAD

**Issue by fuguman** [gshipley/installcentos#19]
Log messages 
--> Scaling simplephp-1 to 1 
error: update acceptor rejected simplephp-1: pods for rc 'grantproject/simplephp-1' took longer than 600 seconds to become available

**Comment by fuguman** [comment]
build messages is
Cloning "https://github.com/gshipley/simplephp.git " ...
	Commit:	59a5b942b7ce4d7066696faa9d83e8b932223d82 (update)
	Author:	gshipley <gshipley@gmail.com>
	Date:	Sun Feb 18 21:50:18 2018 -0500
---> Installing application source...
=> sourcing 20-copy-config.sh ...
---> 12:14:06     Processing additional arbitrary httpd configuration provided by s2i ...
=> sourcing 00-documentroot.conf ...
=> sourcing 50-mpm-tuning.conf ...
=> sourcing 40-ssl-certs.sh ...
Pushing image docker-registry.default.svc:5000/grantproject/simplephp:latest ...
Pushed 0/10 layers, 3% complete
Pushed 1/10 layers, 14% complete
Pushed 2/10 layers, 32% complete
Pushed 3/10 layers, 38% complete
Pushed 4/10 layers, 44% complete
Pushed 5/10 layers, 69% complete
Pushed 6/10 layers, 75% complete
Pushed 7/10 layers, 78% complete
Pushed 8/10 layers, 84% complete
Pushed 9/10 layers, 100% complete
Pushed 10/10 layers, 100% complete
Push successful

**Comment by marekjelen** [comment]
Closing the issue, please reopen if problem persists.
