### ISSUE TITLE
err during running the play book 

### ISSUE THREAD

**Issue by pint12** [gshipley/installcentos#2]
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: RepresenterError: cannot represent an object: htpasswd_auth
fatal: [console.techdope.io]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}

**Comment by pint12** [comment]
TASK [openshift_master : set_fact] *********************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: RepresenterError: cannot represent an object: htpasswd_auth
fatal: [console.techdope.io]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}

**Comment by frgomes** [comment]
I've bumped into the very same issue :-(

**Comment by frgomes** [comment]
Seems to be an ansible issue as per
https://github.com/openshift/openshift-ansible/issues/3146

**Comment by frgomes** [comment]
This solves the issue:

```
#!/bin/bash

yum install -y epel-release
yum install -y docker git wget zile python-cryptography pyOpenSSL.x86_64

## WORKAROUND as per https://github.com/openshift/openshift-ansible/issues/3111
## TODO: yum install ansible
yum install -y "@Development Tools" python2-pip openssl-devel python-devel
pip install -Iv ansible==2.2.0.0
```

**Comment by isreehari** [comment]
I am getting the following error :  " fatal: [console.isreehari.io]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute 'oo_glusterfs_to_config'"} "

**Comment by marekjelen** [comment]
This issue should be closed. The problem was fixed, and there should be no need to the workaround either.
