### ISSUE TITLE
is openshift-ansible broken ?

### ISSUE THREAD

**Issue by baoboa** [gshipley/installcentos#24]
on a fresh bare metal install of centos 7.4 following your instruction i got that in gathering_facts

```
PLAY [Ensure that all non-node hosts are accessible] 
TASK [Gathering Facts]
failed! => {"msg": "module (setup) is missing interpreter line"}
```

looks like a bug of ansible when a setup.py is present in the playbook 
https://github.com/ansible/ansible/issues/34109
renaming installcentos/openshift-ansible/utils/setup.{py,cfg} and installcentos/openshift-ansible/setup.{py,cfg}
solve the problem 
and i am able to finish the installation properly 

the question is how could it work for you or any user of openshift-ansible ?
should i create an issue for openshift-ansible ?
or is it something with my config ?

**Comment by marekjelen** [comment]
The issue if new linked from the openshift-ansible, so it's should be visible in upstream.

I am usign the CentOS/EPEL provided Ansible ... any chance you had some newer version on the machine?

**Comment by baoboa** [comment]
@marekjelen 
sorry i did manage by hacking ( renaming setup.py files ) to install it , i have to refresh the installation to retest it , i could not do it right away.

**Comment by marekjelen** [comment]
ok, please reopen the issue if the problem persists
