### ISSUE TITLE
Upgrade to 3.9

### ISSUE THREAD

**Issue by marekjelen** [gshipley/installcentos#34]
And test the installation process.

**Comment by karvox** [comment]
This line ansible-playbook -i inventory.ini openshift-ansible/playbooks/byo/config.yml not works when try install 3.9 version.

**Comment by ryannix123** [comment]
I received the same error. However, you can increment to 3.7.2, which works.

**Comment by koenhendriks** [comment]
Has this been fixed? Master now has 3.9.0 with a0f165f38fbedcdc1c1274c0bdc50748dc4317d2, is it save to install it?

**Comment by marekjelen** [comment]
yes
