### ISSUE TITLE
admin role

### ISSUE THREAD

**Issue by nickjupp** [gshipley/installcentos#35]
Ran this installer on a Centos build in AWS (Centos official 7), all went fine until the last steps setting up the user
solved adding user by
`**sudo** htpasswd -b /etc/origin/master/htpasswd ${USERNAME} ${PASSWORD}`
but do not have rights to add admin cluster role (have tried adding `--as system:admin`)

So I can login in, but do not have an admin access role

**Comment by marekjelen** [comment]
Try running 

oc login -u system:admin

before adding the cluster-role.

**Comment by nickjupp** [comment]
thanks, have tried - gives
`error: username system:admin is invalid for basic auth`

**Comment by marekjelen** [comment]
Have you tried logging in on the server as system:admin can only login on localhost.

**Comment by nickjupp** [comment]
it's an AWS machine, so via ssh connection.

`[centos@ip-172-31-10-24 installcentos]$ oc login localhost:8443
Authentication required for https://localhost:8443 (openshift)
Username: root
Password: 
Login successful.

You don't have any projects. You can try to create a new project, by running

    oc new-project <projectname>

[centos@ip-172-31-10-24 installcentos]$ oc logout
Logged "root" out on "https://localhost:8443"
[centos@ip-172-31-10-24 installcentos]$ oc login -u system:admin
Authentication required for https://localhost:8443 (openshift)
Username: system:admin
Password: 
error: username system:admin is invalid for basic auth - verify you have provided the correct host and port and that the server is currently running.
error: username system:admin is invalid for basic auth
[centos@ip-172-31-10-24 installcentos]$ `

**Comment by nickjupp** [comment]
Have just run on a local Centos VM using VirtualBox, installed as root user and all worked fine, so seems to be something to do with AWS account permissions.... will continue to investigate as this would be great to spin up on demand!

**Comment by marekjelen** [comment]
Going to investigate, thanks for providing the information.

**Comment by nickjupp** [comment]
re-ran in AWS, added a root password and installed as root - all worked fine so this was the issue. 
CLI access is fine, can `oc describe node` etc, but now can't access web console (at all... no route), which is odd as the previous install did give me the console ok.
I'll keep digging

**Comment by marekjelen** [comment]
Did you configure DNS? It's better to use DNS (at least nip.io) to access the console then plain IP address.

**Comment by marekjelen** [comment]
Seems stale, please reopen if need be.
