### ISSUE TITLE
Ansible in service_catalog is always fail

### ISSUE THREAD

**Issue by macauleycheng** [gshipley/installcentos#38]
I can't success run the script. It always failed at the service_catalog.
It will check the "https://apiserver.kube-service-catalog.svc/healthz" but I find there is no kubenetes POD or service for this address.
I use pure Centos 7.2 minimal version.

Below is my output of ansible message and kubectl get all.

TASK [openshift_service_catalog : wait for api server to be ready] ***********************************************************************************************************
FAILED - RETRYING: wait for api server to be ready (60 retries left).
FAILED - RETRYING: wait for api server to be ready (59 retries left).
FAILED - RETRYING: wait for api server to be ready (58 retries left).
fatal: [192.168.200.40]: FAILED! => {"attempts": 60, "changed": false, "content": "", "msg": "Status code was -1 and not [200]: Request failed: <urlopen error [Errno 111] Con
nection refused>", "redirected": false, "status": -1, "url": "https://apiserver.kube-service-catalog.svc/healthz"}
        to retry, use: --limit @/root/openshift-ansible/playbooks/byo/config.retry

[root@openshift ~]# kubectl get all
NAME                            DOCKER REPO                                                 TAGS      UPDATED
imagestreams/registry-console   docker-registry.default.svc:5000/default/registry-console   latest    3 hours ago

NAME                                 REVISION   DESIRED   CURRENT   TRIGGERED BY
deploymentconfigs/docker-registry    1          1         1         config
deploymentconfigs/registry-console   1          1         0         config
deploymentconfigs/router             5          1         1         config

NAME                      HOST/PORT                                    PATH      SERVICES           PORT      TERMINATION   WILDCARD
routes/docker-registry    docker-registry-default.apps.macauley.com              docker-registry    <all>     passthrough   None
routes/registry-console   registry-console-default.apps.macauley.com             registry-console   <all>     passthrough   None

NAME                         READY     STATUS    RESTARTS   AGE
po/docker-registry-1-b996v   0/1       Error     0          2h
po/router-5-mqzs2            1/1       Running   0          15m

NAME                    DESIRED   CURRENT   READY     AGE
rc/docker-registry-1    1         1         0         2h
rc/registry-console-1   0         0         0         2h
rc/router-1             0         0         0         2h
rc/router-2             0         0         0         2h
rc/router-3             0         0         0         1h
rc/router-4             0         0         0         33m
rc/router-5             1         1         1         15m

NAME                   CLUSTER-IP       EXTERNAL-IP   PORT(S)                   AGE
svc/docker-registry    172.30.82.155    <none>        5000/TCP                  2h
svc/kubernetes         172.30.0.1       <none>        443/TCP,53/UDP,53/TCP     3h
svc/registry-console   172.30.12.197    <none>        9000/TCP                  2h
svc/router             172.30.224.129   <none>        80/TCP,443/TCP,1936/TCP   2h

**Comment by macauleycheng** [comment]
I think it maybe related to my DNS server. I add wildcard symbol "*.apps.maydomain" in DNS A record. This install script run no error.

**Comment by marekjelen** [comment]
thanks for reporting the issue ... can we close it? or do you still experience issues?

**Comment by macauleycheng** [comment]
We can close it.
Thanks

**Comment by marekjelen** [comment]
Thanks
