### ISSUE TITLE
Changing web-console public URL

### ISSUE THREAD

**Issue by hmadhavan** [gshipley/installcentos#43]
Hi,
 I used this project to setup the Openshift in one RHEL 7.5 vm. I had a typo in the env variable for domain and ended up configuring the console URL as " https://console.116.87.123.194.nip.io:8443/"

I would like to know if there is any way to change the public URL. I tried changing the /etc/origin/master/master-config.yaml  and restarting the services, didn't help much.  

Thanks for the help,
H

**Comment by marekjelen** [comment]
Since 3.9 console runs as a separate pod, you need to restart that pod.
