### ISSUE TITLE
[Question] Upgrade OpenShift version

### ISSUE THREAD

**Issue by Enrico204** [gshipley/installcentos#48]
Is it possible to use this script to upgrade a previously installed OpenShift instance with the same script?

**Comment by marekjelen** [comment]
Hi, at this moment it is not possible. The script only sets up production-like cluster in an easy way. We are not planning to handle day-two operations, right @gshipley ?

**Comment by marekjelen** [comment]
Hi, you will need to either follow real installation or set up a separate cluster and migrate. This script is (in foreseeable future) not going to be extended to support upgrading clusters.

**Comment by gshipley** [comment]
Correct.  We don't plan to handle day two operations and only intend this to be a quick way to get everything up and running.
