### ISSUE TITLE
Error at Task - Evaluate Groups - Fail if no etcd hosts group is defined

### ISSUE THREAD

**Issue by m3ssana** [gshipley/installcentos#6]
Hello,

I am receiving the following error. How do i define an etcd group?

TASK [Evaluate groups - Fail if no etcd hosts group is defined] ***********************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Running etcd as an embedded service is no longer supported. If this is a new install please define an 'etcd' group with either one or three hosts. These hosts may be the same hosts as your masters. If this is an upgrade you may set openshift_master_unsupported_embedded_etcd=true until a migration playbook becomes available.\n"}
        to retry, use: --limit @/root/openshift-ansible/playbooks/byo/config.retry

PLAY RECAP ****************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1

Failure summary:

  1. Hosts:    localhost
     Play:     Populate config host groups
     Task:     Evaluate groups - Fail if no etcd hosts group is defined
     Message:  Running etcd as an embedded service is no longer supported. If this is a new install please define an 'etcd' group with either one or three hosts. These hosts may be the same hosts as your masters. If this is an upgrade you may set openshift_master_unsupported_embedded_etcd=true until a migration playbook becomes available.

**Comment by m3ssana** [comment]
i retried this using the included installcentos/inventory.erb with the same issue

**Comment by m3ssana** [comment]
I found this:
https://bugzilla.redhat.com/show_bug.cgi?id=1492682

but I am unsure how to update the inventory

**Comment by rliessum** [comment]
[OSEv3:children]
masters
nodes
etcd

[etcd]
etcd[1-3].openshiftdev.io or single node (can be your master if sufficient resources are available)

**Comment by marekjelen** [comment]
This should be fixed by the latest updates, PR is ready to be merged.

**Comment by gshipley** [comment]
Merged and closing.
