### ISSUE TITLE
how to deploy cluster

### ISSUE THREAD

**Issue by alanxie1129** [gshipley/installcentos#60]
how to deploy cluster

**Comment by marekjelen** [comment]
Deploying multi-node cluster is not supported ATM using this wrapper.

The script wraps the Ansible playbooks for quick single-node deployment. The wrapped playbooks need to be used directly to install real cluster. 

https://github.com/openshift/openshift-ansible

**Comment by marekjelen** [comment]
Closing this issue, feel free to open new one, or reopen in case there are more questions. Thanks
