### ISSUE TITLE
Failed Install and odd STDOUT Messages

### ISSUE THREAD

**Issue by IRobL** [gshipley/installcentos#62]
Hi, I'm on a fresh VM with CentOS 7 (not sure if that's ideal) and I'm seeing some odd messages upon execution of the script:

```
$  curl https://raw.githubusercontent.com/gshipley/installcentos/master/install-openshift.sh -a | /bin/bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5126  100  5126    0     0  17026      0 --:--:-- --:--:-- --:--:-- 17086

* OpenShift version: echo "* Your IP is $IP "
******
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.rackspace.com
```

Notice how the `* OpenShift version: echo "* Your IP is $IP "` bit of things is garbled?  Has anyone else encountered this?  Also, not using the `-a` switch, my terminal never actually prompted me for mandatory variables :/  Maybe I'm missing some key package to run this wrapper?

Also, here's some error snippets from the install process:

```
TASK [Evaluate groups - Fail if no etcd hosts group is defined] ****************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Running etcd as an embedded service is no longer supported. If this is a new install please define an 'etcd' group with either one, three or five hosts. These hosts may be the same hosts as your masters. If this is an upgrade please see https://docs.openshift.com/container-platform/latest/install_config/upgrading/migrating_embedded_etcd.html for documentation on how to migrate from embedded to external etcd.\n"}
	to retry, use: --limit @/home/kentos/openshift-ansible/playbooks/prerequisites.retry
.
.
.
Usage:
	htpasswd [-cimBdpsDv] [-C cost] passwordfile username
	htpasswd -b[cmBdpsDv] [-C cost] passwordfile username password

	htpasswd -n[imBdps] [-C cost] username
	htpasswd -nb[mBdps] [-C cost] username password
 -c  Create a new file.
.
.
.
/bin/bash: line 155: oc: command not found
Failed to restart origin-master-api.service: Unit not found.
******
* Your console is https://console.97.116.33.228.nip.io:echo "* Your password is $PASSWORD "
* Your username is echo "******"
* Your password is echo "* Your domain is $DOMAIN "
*
* Login using:
*
$ oc login -u echo "******" -p echo "* Your domain is $DOMAIN " https://console.97.116.44.1.nip.io:echo "* Your password is $PASSWORD "/
******
/bin/bash: line 170: oc: command not found
```

```

**Comment by koksj** [comment]
On line 142 of the install-openshift.sh script the envsubst command substitutes the wrong values into inventory.ini 

The following work around worked for me:

1) Download install-openshift.sh 
2) Edit install-openshift.sh and comment these lines:
    echo "* Your domain is $DOMAIN "
    echo "* Your IP is $IP "
    echo "* Your username is $USERNAME "
    echo "* Your password is $PASSWORD "
    echo "* OpenShift version: $VERSION "
    #echo "******"
3) run install-openshift.sh  from the local file system.

P.S It's not a fix, just a crude workaround.

**Comment by IRobL** [comment]
Thanks for sharing notes!  I'm doing further poking around, and it seems to possibly have something to do with how piping to `| /bin/bash` works (or rather doesn't).  I'm still unsure why...

**Comment by IRobL** [comment]
Does the rest of the script work for you, @koksj?  The underlying ansible-playbook is hitting this error and the script concludes as follows:

```
TASK [openshift_master_certificates : Create the master server certificate] ******************************************************************************************************************************

TASK [openshift_master_certificates : Generate the loopback master client config] ************************************************************************************************************************
ERROR! |failed expects hostvars is a dict
htpasswd: cannot modify file /etc/origin/master/htpasswd; use '-c' to create it
install-openshift.sh: line 159: oc: command not found
Failed to restart origin-master-api.service: Unit not found.
* Your console is https://console.97.116.33.228.nip.io:8443
* Your username is kentos
* Your password is fuzzypickles
* Login using:
$ oc login -u kentos -p fuzzypickles https://console.97.116.33.228.nip.io:8443/
install-openshift.sh: line 170: oc: command not found
```

I wonder if this project would have better luck locking down the install to specific git commits on it's dependent software projects.

**Comment by koksj** [comment]
@IRobL  I get the exact same error. Spent all day trying to get past it. No such luck yet.

**Comment by IRobL** [comment]
On the second error, I'm following up [here](https://github.com/openshift/openshift-ansible/issues/7596) and making some progress... albeit towards other errors.  

The following commands use the patch mentioned in that thread, but sadly I am halted on another, possibly unrelated error :(

```
sudo su
export PASSWORD='changeme123'
export USERNAME='john'
export DOMAIN='97.116.33.228.nip.io'

curl https://raw.githubusercontent.com/irobl/installcentos/master/install-openshift.sh > install-openshift.sh

chmod 0775 install-openshift.sh
sed -i '/^echo "\**"$/d' install-openshift.sh # just in-case

/bin/bash install-openshift.sh -a
```

Notice it's relying on these two patched up forks in the hopes to produce stability:

- https://github.com/IRobL/installcentos
- https://github.com/IRobL/openshift-ansible

**Comment by sosguthorpe** [comment]
@IRobL Was seeing this exact error. However it has only just crept in over the last week, as this script worked perfectly last week for a fresh Centos 7 install. I think that's because Ansible has upgraded itself from 2.4 to 2.6 somewhere, either in the main package repos of Centos or as a dependency somewhere else. If you haven't already you should maybe submit a pull request to the openshift ansible repo as this patch seems to have fixed it for me.

**Comment by marekjelen** [comment]
not sure why it's happening, but have changed the way the switch between interactive/non-interactive is done and seems to work now. Managed to deploy cluster, but `Logging` failed ... will keep investigating tomorrow.

**Comment by marekjelen** [comment]
OK, with explicitly stating the variable in the inventory file,  the `Logging` installation finished fine. Running

```
curl https://raw.githubusercontent.com/gshipley/installcentos/master/install-openshift.sh | INTERACTIVE=false /bin/bash
```

on a VM with 16G memory gives me a complete and functional deployment.

**Comment by marscydonia** [comment]
Just tried to deploy Openshift on my VM but I get this error now:

`FAILED - RETRYING: wait for api server to be ready (60 retries left).
FAILED - RETRYING: wait for api server to be ready (59 retries left).
FAILED - RETRYING: wait for api server to be ready (58 retries left).
FAILED - RETRYING: wait for api server to be ready (57 retries left).
FAILED - RETRYING: wait for api server to be ready (56 retries left).
FAILED - RETRYING: wait for api server to be ready (55 retries left).
FAILED - RETRYING: wait for api server to be ready (54 retries left).
FAILED - RETRYING: wait for api server to be ready (1 retries left).
fatal: [10.100.0.80]: FAILED! => {"attempts": 60, "changed": false, "content": "", "msg": "Status code was -1 and not [200]: Request failed: <urlopen error [Errno 111] Connection refused>", "redirected": false, "status": -1, "url": "https://apiserver.kube-service-catalog.svc/healthz"}
        to retry, use: --limit @/root/openshift-ansible/playbooks/deploy_cluster.retry

PLAY RECAP *********************************************************************
10.100.0.80                : ok=926  changed=333  unreachable=0    failed=1
localhost                  : ok=13   changed=0    unreachable=0    failed=0


INSTALLER STATUS ***************************************************************
Initialization             : Complete (0:00:10)
Health Check               : Complete (0:00:01)
etcd Install               : Complete (0:01:15)
Master Install             : Complete (0:04:53)
Master Additional Install  : Complete (0:00:28)
Node Install               : Complete (0:02:16)
Hosted Install             : Complete (0:01:13)
Web Console Install        : Complete (0:01:26)
Metrics Install            : Complete (0:01:36)
Logging Install            : Complete (0:02:24)
Service Catalog Install    : In Progress (0:12:12)
        This phase can be restarted by running: playbooks/openshift-service-catalog/config.yml



Failure summary:


  1. Hosts:    10.100.0.80
     Play:     Service Catalog
     Task:     wait for api server to be ready
     Message:  Status code was -1 and not [200]: Request failed: <urlopen error [Errno 111] Connection refused>
Adding password for user marko
cluster role "cluster-admin" added: "marko"
******
* Your console is https://console.internal.mkgraz.ovh:8443
* Your username is marko
* Your password is xxxxxxxxx`

**Comment by marekjelen** [comment]
@marscydonia that can be many things, what does syslog say?

**Comment by koksj** [comment]
@marekjelen I have tested  the script and it worked for me. 
P.S
A big thank you, to you and the other contributors to make this script possible.

**Comment by devops-42** [comment]
Hi all,

any solution for this? After changing the install-openshift.sh script (remove the `echo "**"` lines) I ran into the `oc: command not found` error.

The two errors during the playbook were:

```
PLAY [Ensure that all non-node hosts are accessible] ***************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
fatal: [xx.xx.xx.xx]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n", "unreachable": true}
```

**Comment by koksj** [comment]
@devops-42 

Try downloading the script to your local file system. Don't make any changes to the script. Also download vol.yaml to your local file system. 

Then follow the automaton instructions as detailed in
https://github.com/gshipley/installcentos Readme. Excepect run the script from your local file system.

Just for the record running it from curl worked for me after @marekjelen  made his fixes.

**Comment by devops-42** [comment]
@koksj Thanks, but new errors occur :( Have proceeded as suggested:

```
curl https://raw.githubusercontent.com/gshipley/installcentos/master/install-openshift.sh > install-openshift.sh
curl https://raw.githubusercontent.com/gshipley/installcentos/master/vol.yaml > vol.yaml

export DOMAIN=172......nip.io 
export USERNAME=osadmin
export PASSWORD=********
export VERSION="v3.9.0"
chmod +x install-openshift.sh 
INTERACTIVE=false ./install-openshift.sh 
```

leads to:

```
TASK [Evaluate oo_etcd_to_migrate] *****************************************************************************************************************************************************************************************************************************************
ok: [localhost] => (item=172........)
 [WARNING]: Could not match supplied host pattern, ignoring: oo_lb_to_config

 [WARNING]: Could not match supplied host pattern, ignoring: oo_nfs_to_config


PLAY [Ensure that all non-node hosts are accessible] ***********************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************************************************************************************************************
fatal: [172........]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n", "unreachable": true}

NO MORE HOSTS LEFT *********************************************************************************************************************************************************************************************************************************************************
	to retry, use: --limit @/home/matthias/openshift-ansible/playbooks/prerequisites.retry

PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************************
172........               : ok=1    changed=0    unreachable=1    failed=0   
localhost                  : ok=11   changed=0    unreachable=0    failed=0   


INSTALLER STATUS ***********************************************************************************************************************************************************************************************************************************************************
Initialization             : In Progress (0:00:01)
```

with final error:

```
htpasswd: cannot modify file /etc/origin/master/htpasswd; use '-c' to create it
./install-openshift.sh: line 155: oc: command not found
Failed to restart origin-master-api.service: Unit not found.
******

```

**Comment by devops-42** [comment]
@koksj 

Problem found :) The user account could not login via public key, so the playbook stopped.

Thanks for your help!
