### ISSUE TITLE
unable to read config file: open /etc/origin/node/resolv.conf: no such file or directory

### ISSUE THREAD

**Issue by pranavskurup** [gshipley/installcentos#63]
I am unable to install openshift all in one getting error while restarting node during openshift-node task /etc/origin/node/resolv.conf: no such file or directory

Checked  /etc/origin/node/ directory
it contains following file 

total 44
drwx------.  2 root root 4096 Jul 11 19:13 .
drwx------. 10 root root 4096 Jul 11 19:13 ..
-rw-r--r--.  1 root root 1070 Jul 11 19:12 ca.crt
-rw-------.  1 root root 1313 Jul 11 19:13 node-config.yaml
-rw-r--r--.  1 root root   63 Jul 11 19:13 node-dnsmasq.conf
-rw-r--r--.  1 root root 2258 Jul 11 19:12 server.crt
-rw-------.  1 root root 1675 Jul 11 19:12 server.key
-rw-r--r--.  1 root root 1139 Jul 11 19:12 system:node:xxxxxxxx.crt
-rw-------.  1 root root 1679 Jul 11 19:12 system:node:xxxxxx.key
-rw-------.  1 root root 5866 Jul 11 19:12 system:node:xxxxxxx.kubeconfig

cat node/node-dnsmasq.conf
server=/in-addr.arpa/127.0.0.1
server=/cluster.local/127.0.0.1

any idea why this is happening

**Comment by pranavskurup** [comment]
for dns as per penshift documentation added
PEERDNS=yes
NM_CONTROLLED=yes
in /etc/sysconfig/network-scripts/ifcfg-eth0

**Comment by ryannix123** [comment]
@pranavskurup Do you have ports 80,443, and 8443 open to the world?

**Comment by pranavskurup** [comment]
Yes

**Comment by pranavskurup** [comment]
I tried to debug the code and noticed fowllowing observations

/etc/NetworkManager/dispatcher.d/99-origin-dns.sh creates  /etc/origin/node/resolv.conf file

This script is called during every NetworkManager restart

When i tried to debug 

```
if [[ ${DEVICE_IFACE} == ${def_route_int} ]]; then
```
Above condition fails of eth0

```
[[ '' == xxx.xxx.xxx.xxx ]]
```
Somehow DEVICE_IFACE is empty any idea why this is happening

**Comment by pranavskurup** [comment]
When I removed
```
PEERDNS=yes
```
above line from /etc/sysconfig/network-scripts/ifcfg-eth0
and replaced '**def_route_int**' with '**def_route_ip**' (when i checked log value of **def_route_ip** is **eth0**) in below line 
```
if [[ ${DEVICE_IFACE} == ${def_route_int} ]]; then
```
Now condition evaluates as
```
[[ eth0 == eth0  ]]
```
And resolv.conf is created  at /etc/origin/node/resolv.conf with content 
```
nameserver 8.8.4.4
nameserver 8.8.8.8
```

Is this correct @ryannix123 ?

**Comment by pranavskurup** [comment]
Ok

**Comment by marekjelen** [comment]
Please report to the installer team at https://github.com/openshift/openshift-ansible
