### ISSUE TITLE
Openshift Task to disable legacy master service fails

### ISSUE THREAD

**Issue by dhanugithub** [gshipley/installcentos#66]
Hello,
I have a CentOS minimal install VM running on Proxmox VE in which I am running the script provided by G. Shipley.
I am following G. Shipley's youtube video and also instructions given here.
I run into following error:

Task [Openshift_master: Disable the legacy maszter service if it exists]
fatal: [192.168.10.216]: FAILED! => {"changed": false, "msg": "Could not find the                                                                                                          requested service origin-master: host"}
Although this error doesn't seem to affect any implementation or later working of openshift but I am curious to know why this appears. Even in my other implementions (1 master VM and 1 node VM) I have same error and several dependency failures.

Also, I have a doubt. According to the Openshift documentation, if we are using "containerized=true", then "docker run" command should be used to implement each service as a separate docker container. But this and many other documents simply follow ansible-playbook command which is suitable for RPM installation.
Any help is appreciated.
Thank you.

**Comment by marekjelen** [comment]
Hi, you will need to ask at https://github.com/openshift/openshift-ansible.
