### ISSUE TITLE
OpenShift Failed installation at "Install Ceph storage plugin dependencies"

### ISSUE THREAD

**Issue by imranrazakhan** [gshipley/installcentos#67]
Enviornment: VM with CentOs 7.5

ASK [openshift_node : Install Ceph storage plugin dependencies] *********************************************************************************************************
FAILED - RETRYING: Install Ceph storage plugin dependencies (3 retries left).
FAILED - RETRYING: Install Ceph storage plugin dependencies (2 retries left).
FAILED - RETRYING: Install Ceph storage plugin dependencies (1 retries left).
fatal: [10.0.2.15]: FAILED! => {"attempts": 3, "changed": false, "module_stderr": "Shared connection to 10.0.2.15 closed.\r\n", "module_stdout": "error: rpmdb: BDB0113 Thread/proce
ss 28774/140193218025280 failed: BDB1507 Thread died in Berkeley DB library\r\nerror: db5 error(-30973) from dbenv->failchk: BDB0087 DB_RUNRECOVERY: Fatal error, run database recov
ery\r\nerror: cannot open Packages index using db5 -  (-30973)\r\nerror: cannot open Packages database in /var/lib/rpm\r\nTraceback (most recent call last):\r\n  File \"/tmp/ansibl
e_xLSJTe/ansible_module_yum.py\", line 1509, in <module>\r\n    main()\r\n  File \"/tmp/ansible_xLSJTe/ansible_module_yum.py\", line 1470, in main\r\n    my.conf\r\n  File \"/usr/l
ib/python2.7/site-packages/yum/__init__.py\", line 1078, in <lambda>\r\n    conf = property(fget=lambda self: self._getConfig(),\r\n  File \"/usr/lib/python2.7/site-packages/yum/__
init__.py\", line 349, in _getConfig\r\n    startupconf = config.readStartupConfig(fn, root, releasever)\r\n  File \"/usr/lib/python2.7/site-packages/yum/config.py\", line 1112, in
 readStartupConfig\r\n    startupconf.distroverpkg)\r\n  File \"/usr/lib/python2.7/site-packages/yum/config.py\", line 1254, in _getsysver\r\n    raise Errors.YumBaseError(\"Error:
 \" + str(e))\r\nyum.Errors.YumBaseError: Error: rpmdb open failed\r\n", "msg": "MODULE FAILURE", "rc": 1}

**Comment by Herve-ross** [comment]
I had same kind of issue with the Task "Install NFS storage plugin dependencies".
Looking at the playbook, this one use "package" module.
It should use apt or yum depending on your OS.
I installed the missing package with simple manual yum install.
Look like package module doesn't work properly.

**Comment by imranrazakhan** [comment]
Yes with manual installation it works.

**Comment by marekjelen** [comment]
Hi, please report at https://github.com/openshift/openshift-ansible where the installer resides.
