### ISSUE TITLE
DOMAIN name issue while installing

### ISSUE THREAD

**Issue by imranrazakhan** [gshipley/installcentos#68]
Following your video i install openshift with domain like

export DOMAIN=${DOMAIN:="$(curl -s ipinfo.io/ip).nip.io"}

above command produce result like 85.80.161.23.nip.io

After successful installation i am not able to access console, i verified domain and found that now system is showing values like below 
77.79.13.222.nip.io

How to manage this situation?

**Comment by marekjelen** [comment]
The command is there to make a guess what your IP might be. If the detection does not work, the domain name has to be set manually.

**Comment by vitruxv** [comment]
What I found to work as a work around is to clone the script and run the install-openshift.sh script and it prompts for the variables it needs.  Those variables have worked vs exporting.
