### ISSUE TITLE
missing origin-clients & vol.yaml

### ISSUE THREAD

**Issue by Herve-ross** [gshipley/installcentos#69]
Little feedback from my experience using you script.
1. During the creation of persistent volume, the script need the file vol.yaml as template to create 200 PV.
The script do no copy vol.yaml from git to you local host , so you have to copy it manually.
2. Creating PV and login to openshift require the command "oc" from missing package origin-clients. 
origin-clients is not a dependency or installed by the script. Can be fix by installing this one after ansible playbooks. Ansible playbooks take care to create the repository "CentOS OpenShift Origin" where the package origin-clients is available.
3. Run twice the script is disruptive for docker if you use $DISK.
If you want to use and additional disk for docker, the script take care to wipefs and delete /var/lib/docker folder. If you miss something and run the script a second time, the script will break the storage and docker will be not able to start. You end up with a busy storage unable to be deleted and docker not able to start.

Otherwise, this is a very good script and I am an happy user of OpenShift Origine, thanks to you !

**Comment by marekjelen** [comment]
1. fixed, thanks!
2. `oc` is installed on the system by the installer
3. yes, that is expected behaviour as stated in the docs
