### ISSUE TITLE
3.10 support?

### ISSUE THREAD

**Issue by ryannix123** [gshipley/installcentos#72]
Has anyone tried install 3.10?

**Comment by gshipley** [comment]
working on fixing it today

**Comment by gshipley** [comment]
3.10 is working now in the 3.10 branch.  I will get it merged later tonight or early tomorrow once I have time to test it a bit more.  If using the branch:

git clone THE_REPO
cd installcentos
git checkout 3.10
export SCRIPT_REPO=https://raw.githubusercontent.com/gshipley/installcentos/3.10
./install-openshift.sh

**Comment by gshipley** [comment]
master branch updated.
