### ISSUE TITLE
openshift network is not working

### ISSUE THREAD

**Issue by dhanugithub** [gshipley/installcentos#73]
Hello,
I have installed Openshift Origin 3.9 using the repo. And deployed a customized application in it. But when I try to access the application using route, it does not work.
I have installed openshift in a VM on Proxmox VE. (80G disk, 48G RAM, 1 socket & 6 cores, bridged networking)
When I check for the interfaces on my VM, (using ip a) I see that docker0, br0, ovs-system are in DOWN state, while tun0 is in UNKNOWN state.
This is the output of "ip a"

[root@openshift ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 62:15:5b:9f:58:7b brd ff:ff:ff:ff:ff:ff
    inet 192.168.10.216/24 brd 192.168.10.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::a9de:8d6b:44be:2f4e/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:81:45:d4:52 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
4: ovs-system: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether d2:ea:0c:27:5b:47 brd ff:ff:ff:ff:ff:ff
8: br0: <BROADCAST,MULTICAST> mtu 1450 qdisc noop state DOWN group default qlen 1000
    link/ether 92:c8:a1:94:7a:45 brd ff:ff:ff:ff:ff:ff
9: vxlan_sys_4789: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 65520 qdisc noqueue master ovs-system state UNKNOWN group default qlen 1000
    link/ether 2a:3b:49:ca:e3:99 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::283b:49ff:feca:e399/64 scope link
       valid_lft forever preferred_lft forever
10: tun0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 16:b2:34:58:81:a4 brd ff:ff:ff:ff:ff:ff
    inet 10.128.0.1/23 brd 10.128.1.255 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 fe80::14b2:34ff:fe58:81a4/64 scope link
       valid_lft forever preferred_lft forever
11: veth28b72cfe@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master ovs-system state UP group default
    link/ether 32:63:f5:60:ec:33 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::3063:f5ff:fe60:ec33/64 scope link
       valid_lft forever preferred_lft forever
12: vethec8de5f5@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master ovs-system state UP group default
    link/ether f2:78:5a:7b:03:9b brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::f078:5aff:fe7b:39b/64 scope link
       valid_lft forever preferred_lft forever
13: vethcf4bab48@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master ovs-system state UP group default
    link/ether 12:2f:61:71:8b:8e brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::102f:61ff:fe71:8b8e/64 scope link
       valid_lft forever preferred_lft forever
14: vethba340af9@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master ovs-system state UP group default
    link/ether 46:68:af:7f:53:34 brd ff:ff:ff:ff:ff:ff link-netnsid 3
    inet6 fe80::4468:afff:fe7f:5334/64 scope link
       valid_lft forever preferred_lft forever
15: vethaa9933bb@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master ovs-system state UP group default
    link/ether aa:83:d9:c7:6c:a8 brd ff:ff:ff:ff:ff:ff link-netnsid 4
    inet6 fe80::a883:d9ff:fec7:6ca8/64 scope link
       valid_lft forever preferred_lft forever
16: vethd81db48b@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master ovs-system state UP group default
    link/ether 56:f8:df:0c:65:46 brd ff:ff:ff:ff:ff:ff link-netnsid 5
    inet6 fe80::54f8:dfff:fe0c:6546/64 scope link
       valid_lft forever preferred_lft forever
17: veth2d069743@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master ovs-system state UP group default
    link/ether d6:d8:bc:5d:18:40 brd ff:ff:ff:ff:ff:ff link-netnsid 6
    inet6 fe80::d4d8:bcff:fe5d:1840/64 scope link
       valid_lft forever preferred_lft forever
18: veth1eb83fb0@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master ovs-system state UP group default
    link/ether 8a:9d:b5:15:7a:72 brd ff:ff:ff:ff:ff:ff link-netnsid 7
    inet6 fe80::889d:b5ff:fe15:7a72/64 scope link
       valid_lft forever preferred_lft forever
19: veth07290fcc@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master ovs-system state UP group default
    link/ether 3a:da:06:eb:26:e9 brd ff:ff:ff:ff:ff:ff link-netnsid 8
    inet6 fe80::38da:6ff:feeb:26e9/64 scope link
       valid_lft forever preferred_lft forever
20: vetha2a639f2@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master ovs-system state UP group default
    link/ether 72:83:98:58:08:33 brd ff:ff:ff:ff:ff:ff link-netnsid 9
    inet6 fe80::7083:98ff:fe58:833/64 scope link
       valid_lft forever preferred_lft forever
21: vethd181d9e2@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master ovs-system state UP group default
    link/ether 66:a2:b8:70:4c:02 brd ff:ff:ff:ff:ff:ff link-netnsid 10
    inet6 fe80::64a2:b8ff:fe70:4c02/64 scope link
       valid_lft forever preferred_lft forever
22: veth0fbae888@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master ovs-system state UP group default
    link/ether a2:62:45:ed:73:13 brd ff:ff:ff:ff:ff:ff link-netnsid 11
    inet6 fe80::a062:45ff:feed:7313/64 scope link
       valid_lft forever preferred_lft forever
23: veth696055ef@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master ovs-system state UP group default
    link/ether 3a:2b:56:1d:6a:96 brd ff:ff:ff:ff:ff:ff link-netnsid 12
    inet6 fe80::382b:56ff:fe1d:6a96/64 scope link
       valid_lft forever preferred_lft forever
24: vethcb4caedb@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master ovs-system state UP group default
    link/ether c6:bf:79:14:bb:fd brd ff:ff:ff:ff:ff:ff link-netnsid 13
    inet6 fe80::c4bf:79ff:fe14:bbfd/64 scope link
       valid_lft forever preferred_lft forever

I haven't changed any default configuration while installing Openshift.
Can anyone please guide me through this.
Thank you.

**Comment by dhanugithub** [comment]
Also, my etcd is in masked state.
systemctl status etcd
● etcd.service
   Loaded: masked (/dev/null; bad)
   Active: inactive (dead)

is it normal behavior or an error??

**Comment by marekjelen** [comment]
Please try with the new 3.11 release.
