### ISSUE TITLE
Unable to pull  etcd image from "registry.fedoraproject.org/latest/etcd"

### ISSUE THREAD

**Issue by endejoli** [gshipley/installcentos#74]
fatal: [10.8.87.185]: FAILED! => {"changed": false, "cmd": ["docker", "pull", "registry.fedoraproject.org/latest/etcd"], "delta": "0:00:01.606210", "end": "2018-08-29 06:33:59.951167", "msg": "non-zero return code", "rc": 1, "start": "2018-08-29 06:33:58.344957", "stderr": "error pulling image configuration: Get https://cdn.registry.fedoraproject.org/v2/f27/etcd/blobs/sha256:6c1ecdb769b7e0d21f87aa7d5bd0bbd7d456ff802ac03edb1903e65002d89ea8: EOF", "stderr_lines": ["error pulling image configuration: Get https://cdn.registry.fedoraproject.org/v2/f27/etcd/blobs/sha256:6c1ecdb769b7e0d21f87aa7d5bd0bbd7d456ff802ac03edb1903e65002d89ea8: EOF"], "stdout": "Using default tag: latest\nTrying to pull repository registry.fedoraproject.org/latest/etcd ... \nlatest: Pulling from registry.fedoraproject.org/latest/etcd\nff3dab903f92: Pulling fs layer\nf34e1517e3dd: Pulling fs layer", "stdout_lines": ["Using default tag: latest", "Trying to pull repository registry.fedoraproject.org/latest/etcd ... ", "latest: Pulling from registry.fedoraproject.org/latest/etcd", "ff3dab903f92: Pulling fs layer", "f34e1517e3dd: Pulling fs layer"]}

**Comment by marekjelen** [comment]
can not reproduce
