### ISSUE TITLE
What is the process to install master and node on dedicate VMs

### ISSUE THREAD

**Issue by mpangera** [gshipley/installcentos#78]
First of all thank you for your contribution,  I am able to install when I used a single VM for all the services.

But this script is not working when I used dedicated VMs for master and node. Is there any addition changes required or this project doesn't support a multi node cluster ?

Thanks,
Mahesh.

**Comment by walidshaari** [comment]
how does your Ansible inventory file looks like? what changes did you make?

**Comment by marekjelen** [comment]
Hi, please follow the instructions at https://github.com/openshift/openshift-ansible .. we only focus on single node all-in-one clusters.
