### ISSUE TITLE
Unable to connect to the server: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by ryannix123** [gshipley/installcentos#79]
Just FYI, if you receive this error when installing something such as a service catalog, here is the fix.

Issue
Unable to see the projects, nodes, services when using oc command.
Getting same error in oc adm diagnostics.

`ERROR: [CED1008 from controller openshift/origin/pkg/oc/admin/diagnostics/cluster.go]
       Unknown error testing cluster-admin access for context 'default/mycluster.com:8443/sadmin':
       Post https://mycluster.com:8443/apis/authorization.k8s.io/v1/selfsubjectaccessreviews: x509: certificate signed by unknown authority
       
ERROR: [CED1008 from controller openshift/origin/pkg/oc/admin/diagnostics/cluster.go]
       Unknown error testing cluster-admin access for context 'default/mycluster.com:8443/system:admin':
       Post https://mycluster.com:8443/apis/authorization.k8s.io/v1/selfsubjectaccessreviews: x509: certificate signed by unknown authority`

**Resolution**
Backup ~/.kube/config file on master.

**Raw**
# mv ~/.kube/config /tmp/kube_config_backup
Copy config from /etc/origin/master/admin.kubeconfig and then retry oc command.

**Raw**
# cp /etc/origin/master/admin.kubeconfig ~/.kube/config
Diagnostic Steps
Verify that cluster is up and running and working as expected.
Raw
# oc status --config=/etc/origin/master/admin.kubeconfig
# oc get nodes --config=/etc/origin/master/admin.kubeconfig

**Comment by rkpisanu** [comment]
The error is generic error. In my case the reason is regarding the configuration of corporate proxy.

**Comment by marekjelen** [comment]
moved your howto to the project wiki, thanks @ryannix123 

https://github.com/gshipley/installcentos/wiki/Unknown-certs-by-ryannix123
