### ISSUE TITLE
origin-metrics-cassandra - incorrect tags?

### ISSUE THREAD

**Issue by A-Kimpton** [gshipley/installcentos#80]
Problem:
Followed the video guide, but some of the initial containers are not running.

So I've followed the guide, but I'm having a few issues with some of the configuration and setup. The only thing I did to deviate from the video guide was to set the pc name from localhost.localdomain to okd-master

<img width="740" alt="im1" src="https://user-images.githubusercontent.com/32307851/45778604-e9c1d500-bc50-11e8-8fdd-6acecbdfa509.png">

So as you can see from the screenshot, some of the initial containers are not running due to various reasons, I investigated one with:

`oc describe pods hawkular-cassandra-1-xbnzx`

Which gave this output:
<img width="794" alt="im2" src="https://user-images.githubusercontent.com/32307851/45778665-1ece2780-bc51-11e8-9c51-c55ef481584d.png">

So I looked up this container on docker: https://hub.docker.com/r/openshift/origin-metrics-cassandra/tags/

And it looks like the v3.10 tag does not exist. Not sure where I should change this in the config. I've also noticed that the entire metrics thing is not running either.

Do you guys have a support/casual chat group on discord or slack? I'm new to sys-admin related tools, currently studying a degree in computer science, and we don't really cover this type of content.

****** EDIT ******
Looks like origin-metrics-hawkular is also missing the v3.10 tag, but just like the other one, there is a v3.11 tag.
logging-es-data-master-vhdm73pf-1-deploy -- looks like it pulls from https://hub.docker.com/r/openshift/origin-deployer/tags/ and it wants a v3.10.0 and that does actually exist, but it still errored... here's the output:
<img width="793" alt="im3" src="https://user-images.githubusercontent.com/32307851/45779736-b896d400-bc53-11e8-8f7a-aa23b80fdc66.png">

Not sure why that one crashes. It would be really handy if someone could show me how to debug this :D

**Comment by A-Kimpton** [comment]
Okay so I feel like this was me completing thew 'rubber ducky' technique online - but I've managed to changed the resources from v3.10 to v3.11 in the tags by editing the YAML files using the gui :D 

<img width="862" alt="im4" src="https://user-images.githubusercontent.com/32307851/45781878-34474f80-bc59-11e8-835b-5212fffd70fc.png">

But now it complains about the metrics scheme, and the container it points to, no longer exists! Currently trying someone elses container...

**Comment by A-Kimpton** [comment]
Pod: logging-es-data

So from the failed state I initiated the deployment of the pod: this caused the creation of a new pod.
<img width="705" alt="im5" src="https://user-images.githubusercontent.com/32307851/45782532-28f52380-bc5b-11e8-9fea-f374b4fd04f2.png">

Which as you can see is left in the pending state: this is apparently because of a memory issue. Looking into this, I noticed that my VM is using a ridiculous amount of memory just existing. Its currently using 11gb even though I assigned it 8gb in Hyper V - but I think dynamic memory has kicked in, and it's bumped it up to 11gb - Which even if it had to, 11gb is a ridiculous amount to be using when there's not even an application deployed yet...

<img width="436" alt="im6" src="https://user-images.githubusercontent.com/32307851/45782670-88533380-bc5b-11e8-909c-6a5165941f4b.png">

<img width="348" alt="im7" src="https://user-images.githubusercontent.com/32307851/45782708-9e60f400-bc5b-11e8-8287-e632548d3939.png">

Looks like this es pod is requesting under 100mb of ram, and cannot reserve it. Not sure why mem usage is so high. Please advise :)

**Comment by marekjelen** [comment]
Metrics seem to be OK in v3.11, but logging image name/tags are not correct, need to collect info and report an issue. Also logging now sets the minimum memory to 16G, in #97 the limit for logging is updated to handle that.
