### ISSUE TITLE
Can't create simple test php project after install

### ISSUE THREAD

**Issue by akumar2812** [gshipley/installcentos#82]
Cloning "https://github.com/gshipley/simplephp.git " ... 	Commit:	4e0d96ca345308b2dad8766d31f0cd0e00dab4c1 (Test) 	Author:	Grant Shipley <gshipley@gmail.com> 	Date:	Thu Aug 23 19:24:02 2018 -0400
--
  | pulling image error : Get https://docker-registry.default.svc:5000/v2/:  net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  | error: build error: unable to get docker-registry.default.svc:5000/openshift/php@sha256:f6a4a2d6286daacc64ecce919411e42acab6b59f8cba6b04dcc4b79e1a027a73

**Comment by marekjelen** [comment]
That looks like the registry did not get deployed correctly. Check the `docker ps` and try to provide information why the registry is failing and reopen, or better try a clean installation with 3.11 :)
