### ISSUE TITLE
How to use your own ssl certs ? 

### ISSUE THREAD

**Issue by akumar2812** [gshipley/installcentos#83]
You mentioned in the video about using a valid ssl cert... how would one go about doing this?

**Comment by marekjelen** [comment]
There is a documentation on this topic:

https://docs.okd.io/latest/install_config/certificate_customization.html

**Comment by nadilas** [comment]
After creating a wildcard certificate for `*.apps.my.domain` and editing the `inventory.ini` according to https://docs.okd.io/latest/install_config/certificate_customization.html#configuring-custom-certificates-wildcard using the `deploy_router.yaml` . This fixed all the secure routes in the cluster e.g. `home-assistant.apps.my.domain`.

One issue still remains, when switching to `Cluster Console` it keeps redirecting to the login screen. In the logs for the `console` pod are the following entries:
```
2019/02/6 22:04:26 auth: unable to verify auth code with issuer: Post https://console.janosveres.eu:8443/oauth/token:  x509: certificate signed by unknown authority
--
2019/02/6 22:04:26 server: authentication failed: unauthenticated
```

Any ideas?
