### ISSUE TITLE
error when creating "oc_vol.yaml": Post https://127.0.0.1:8443/api/v1/persistentvolumes: dial tcp 127.0.0.1:8443: getsockopt: connection refused

### ISSUE THREAD

**Issue by max-dicson-cf** [gshipley/installcentos#84]
TASK [etcd : Create the server csr] *********************************************************************************************************************************************************
fatal: [0 -> 0]: FAILED! => {"changed": true, "cmd": ["openssl", "req", "-new", "-keyout", "server.key", "-config", "/etc/etcd/ca/openssl.cnf", "-out", "server.csr", "-reqexts", "etcd_v3_req", "-batch", "-nodes", "-subj", "/CN=ip-172-31-95-35.ec2.internal"], "delta": "0:00:00.005700", "end": "2018-09-25 18:24:13.815184", "msg": "non-zero return code", "rc": 1, "start": "2018-09-25 18:24:13.809484", "stderr": "Error Loading request extension section etcd_v3_req\n139869925455760:error:220A4076:X509 V3 routines:a2i_GENERAL_NAME:bad ip address:v3_alt.c:476:value=0\n139869925455760:error:22098080:X509 V3 routines:X509V3_EXT_nconf:error in extension:v3_conf.c:95:name=subjectAltName, value=IP:0,DNS:ip-172-31-95-35.ec2.internal", "stderr_lines": ["Error Loading request extension section etcd_v3_req", "139869925455760:error:220A4076:X509 V3 routines:a2i_GENERAL_NAME:bad ip address:v3_alt.c:476:value=0", "139869925455760:error:22098080:X509 V3 routines:X509V3_EXT_nconf:error in extension:v3_conf.c:95:name=subjectAltName, value=IP:0,DNS:ip-172-31-95-35.ec2.internal"], "stdout": "", "stdout_lines": []}

NO MORE HOSTS LEFT **************************************************************************************************************************************************************************
        to retry, use: --limit @/opt/installcentos/openshift-ansible/playbooks/deploy_cluster.retry

PLAY RECAP **********************************************************************************************************************************************************************************
0                          : ok=162  changed=58   unreachable=0    failed=1
localhost                  : ok=12   changed=0    unreachable=0    failed=0

INSTALLER STATUS ****************************************************************************************************************************************************************************
Initialization              : Complete (0:00:16)
        [DEPRECATION WARNING]: The following are deprecated variables and will be no longer be used in the next minor release. Please update your inventory accordingly.
        openshift_node_kubelet_args
Health Check                : Complete (0:00:07)
Node Bootstrap Preparation  : Complete (0:02:02)
etcd Install                : In Progress (0:00:14)
        This phase can be restarted by running: playbooks/openshift-etcd/config.yml

Failure summary:

  1. Hosts:    0
     Play:     Create etcd server certificates for etcd hosts
     Task:     Create the server csr
     Message:  non-zero return code
Adding password for user xxxxxxxxx
The connection to the server 127.0.0.1:8443 was refused - did you specify the right host or port?
error: error when creating "oc_vol.yaml": Post https://127.0.0.1:8443/api/v1/persistentvolumes: dial tcp 127.0.0.1:8443: getsockopt: connection refused
created volume 1
error: error when creating "oc_vol.yaml": Post https://127.0.0.1:8443/api/v1/persistentvolumes: dial tcp 127.0.0.1:8443: getsockopt: connection refused
created volume 2
..................................
error: error when creating "oc_vol.yaml": Post https://127.0.0.1:8443/api/v1/persistentvolumes: dial tcp 127.0.0.1:8443: getsockopt: connection refused
created volume 200
******
* Your console is https://console.xxxxxxxxx.com:8443
* Your username is xxxxxxx
* Your password is xxxxxxxxxx
*
* Login using:
*
$ oc login -u xxxxxxx -p xxxxxxx https://console.xxxxxxxx.com:8443/
******
error: dial tcp: lookup console.evialperu.com on 172.31.95.35:53: no such host - verify you have provided the correct host and port and that the server is currently running.
[root@ip-172-31-95-35 installcentos]# error when creating "oc_vol.yaml": Post https://127.0.0.1:8443/api/v1/persistentvolumes: dial tcp 127.0.0.1:8443: getsockopt: connection refused

**Comment by max-dicson-cf** [comment]
IP is local ip or public ip ? 

[root@ip-172-31-95-35 centos]# export IP=${IP:="$(ip route get 8.8.8.8 | awk '{print $NF; exit}')"}
[root@ip-172-31-95-35 centos]# echo $IP
0

**Comment by max-dicson-cf** [comment]
$ ip route get 255.255.255.255 | grep -Po '(?<=src )(\d{1,3}.){4}'
192.168.223.129

UPDATE THIS

**Comment by marekjelen** [comment]
Can you please try again with the updates we have done recently? 

In case the problem would persist, please reopen.
