### ISSUE TITLE
import_playbook' is not a valid attribute for a Play

### ISSUE THREAD

**Issue by elasti-ronenc** [gshipley/installcentos#9]
hi ,
i am trying to deploy using the install script and i am getting this error:
import_playbook' is not a valid attribute for a Play

**Comment by elasti-ronenc** [comment]
ERROR! 'import_playbook' is not a valid attribute for a Play

The error appears to have been in '/root/workspace/openshift-ansible/playbooks/init/main.yml': line 16, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- import_playbook: evaluate_groups.yml
  ^ here

**Comment by marekjelen** [comment]
How do you run the `ansible-playbook`?

**Comment by cameronkerrnz** [comment]
Sounds like you're not using Ansible 2.4.

http://docs.ansible.com/ansible/latest/import_playbook_module.html

'import-playbook' was introduced in Ansible 2.4

**Comment by cameronkerrnz** [comment]
The cause would likely be that the install script does not check the version of ansible currently installed.

    which ansible || pip install -Iv ansible

**Comment by marekjelen** [comment]
It should be checked by the playbooks.
