### ISSUE TITLE
No package matching 'origin-node-3.11*'

### ISSUE THREAD

**Issue by Juancarlosmartin10** [gshipley/installcentos#93]
When I try to deploy the new version, 'install-openshift' throws an error:

FAILED! => {"attempts": 3, "changed": false, "msg": "No package matching 'origin-node-3.11*' found available, installed or updated", "rc": 126, "results": ["No package matching 'origin-node-3.11*' found available, installed or updated"]}.

¿Someone have tried to deploy the new version?

Thank you in advance

**Comment by hirenvadalia** [comment]
@Juancarlosmartin10 see this https://github.com/openshift/openshift-ansible/issues/9875#issuecomment-429460978

**Comment by oveits** [comment]
@Juancarlosmartin10: I had the same problem and I went back to the last working commit for 3.10. 

However, I have found this comment of matihost in https://github.com/openshift/openshift-ansible/issues/9875#issuecomment-429967431 (it is another comment in the same issue report @hirenvadalia was pointing to).
 It suggests to add
```
openshift_additional_repos=[{'id': 'centos-okd-ci', 'name': 'centos-okd-ci', 'baseurl' :'https://rpms.svc.ci.openshift.org/openshift-origin-v3.11', 'gpgcheck' :'0', 'enabled' :'1'}]
```
in the inventory file. Could you please try it and report the results?

**Comment by Juancarlosmartin10** [comment]
@oveits I am following this issue in your link, but for me doen.t not work this fix.

I get the same error when I add this line to my inventory file :(

**Comment by Juancarlosmartin10** [comment]
@oveits This worked form me :D 
Thank you.

Close the issue

**Comment by kavana-14** [comment]
while running the,
ansible-playbook -i inventory.ini openshift-ansible/playbooks/deploy_cluster.yml
I'm getting the below error.
I'm using Fedora OS
ansible version core 2.16.6
python version = 3.12.3
jinja version = 3.1.4
```
TASK [openshift_node : Install node, clients, and conntrack packages] ******************************************************************
FAILED - RETRYING: [node1.kavana.io]: Install node, clients, and conntrack packages (3 retries left).
FAILED - RETRYING: [node1.kavana.io]: Install node, clients, and conntrack packages (2 retries left).
FAILED - RETRYING: [node1.kavana.io]: Install node, clients, and conntrack packages (1 retries left).
fatal: [node1.kavana.io]: FAILED! => {"attempts": 3, "changed": false, "failures": ["No package origin-3.11 available.", "No package origin-hyperkube-3.11 available.", "No package origin-node-3.11 available.", "No package origin-clients-3.11 available."], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}

PLAY RECAP *****************************************************************************************************************************
console.kavana.io          : ok=48   changed=2    unreachable=0    failed=0    skipped=61   rescued=0    ignored=0
localhost                  : ok=12   changed=0    unreachable=0    failed=0    skipped=4    rescued=0    ignored=0
node1.kavana.io            : ok=51   changed=5    unreachable=0    failed=1    skipped=77   rescued=0    ignored=0

INSTALLER STATUS ***********************************************************************************************************************
Initialization              : Complete (0:01:23)
Health Check                : Complete (0:00:02)
Node Bootstrap Preparation  : In Progress (0:01:48)
        This phase can be restarted by running: playbooks/openshift-node/bootstrap.yml

Failure summary:

  1. node1.kavana.io
     Configure nodes
     Install node, clients, and conntrack packages
     Failed to install some of the specified packages
```
